import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Download, Package, TestTube, Monitor, Globe, Smartphone, FileArchive } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import JSZip from 'jszip';

interface ProjectDownloaderProps {
  isVisible: boolean;
  onClose: () => void;
  projectName?: string;
  fileContents?: Record<string, string>;
}

export const ProjectDownloader: React.FC<ProjectDownloaderProps> = ({ 
  isVisible, 
  onClose,
  projectName: initialProjectName = 'MyApp',
  fileContents = {}
}) => {
  const [projectType, setProjectType] = useState<'react' | 'pc' | 'mobile'>('react');
  const [projectName, setProjectName] = useState(initialProjectName);
  const [version, setVersion] = useState('1.0.0');
  const [offlineCapable, setOfflineCapable] = useState(true);
  const [includeTests, setIncludeTests] = useState(true);
  const [installerType, setInstallerType] = useState<'msi' | 'exe' | 'dmg' | 'deb' | 'apk' | 'ipa' | 'wap'>('exe');
  const [mobileType, setMobileType] = useState<'android' | 'ios' | 'wap'>('wap');
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();

  if (!isVisible) return null;

  const generatePackageJson = () => {
    return JSON.stringify({
      name: projectName.toLowerCase().replace(/\s+/g, '-'),
      version,
      private: true,
      type: "module",
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
        ...(includeTests && { test: "vitest" })
      },
      dependencies: {
        "react": "^18.3.1",
        "react-dom": "^18.3.1",
        "react-router-dom": "^6.30.1",
        "@radix-ui/react-slot": "^1.2.3",
        "class-variance-authority": "^0.7.1",
        "clsx": "^2.1.1",
        "lucide-react": "^0.462.0",
        "tailwind-merge": "^2.6.0",
        "tailwindcss-animate": "^1.0.7"
      },
      devDependencies: {
        "@types/react": "^18.3.0",
        "@types/react-dom": "^18.3.0",
        "@vitejs/plugin-react": "^4.3.1",
        "autoprefixer": "^10.4.19",
        "postcss": "^8.4.38",
        "tailwindcss": "^3.4.3",
        "typescript": "^5.4.5",
        "vite": "^5.2.11",
        ...(includeTests && { "vitest": "^1.6.0" })
      }
    }, null, 2);
  };

  const generateViteConfig = () => {
    return `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  ${offlineCapable ? `
  // PWA configuration for offline support
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          vendor: ['react', 'react-dom', 'react-router-dom'],
        },
      },
    },
  },` : ''}
});`;
  };

  const generateIndexHtml = () => {
    return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="${projectName} - Built with Matrix DevStudio" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>`;
  };

  const generateReadme = () => {
    return `# ${projectName}

Built with **Matrix DevStudio** - A Cyberpunk IDE Experience

## Version
${version}

## Features
${offlineCapable ? '- ✅ Offline Capable (PWA)' : ''}
${includeTests ? '- ✅ Full Testing Suite' : ''}
- ✅ React 18
- ✅ TypeScript
- ✅ Tailwind CSS
- ✅ Vite Build System

## Getting Started

\`\`\`bash
# Install dependencies
npm install

# Start development server
npm run dev

# Build for production
npm run build
${includeTests ? `
# Run tests
npm test` : ''}
\`\`\`

## Project Structure

\`\`\`
${projectName}/
├── src/
│   ├── components/
│   ├── hooks/
│   ├── lib/
│   └── main.tsx
├── public/
├── package.json
└── vite.config.ts
\`\`\`

---
*Generated by Matrix DevStudio*
`;
  };

  const generateServiceWorker = () => {
    if (!offlineCapable) return null;
    return `// Service Worker for offline support
const CACHE_NAME = '${projectName.toLowerCase()}-v${version}';
const urlsToCache = [
  '/',
  '/index.html',
  '/src/main.tsx',
];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(urlsToCache))
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request)
      .then((response) => response || fetch(event.request))
  );
});`;
  };

  const handleDownload = async () => {
    setIsGenerating(true);
    
    try {
      const zip = new JSZip();
      
      // Root folder
      const projectFolder = zip.folder(projectName);
      if (!projectFolder) throw new Error('Failed to create project folder');

      // Add package.json
      projectFolder.file('package.json', generatePackageJson());
      
      // Add vite.config.ts
      projectFolder.file('vite.config.ts', generateViteConfig());
      
      // Add index.html
      projectFolder.file('index.html', generateIndexHtml());
      
      // Add README.md
      projectFolder.file('README.md', generateReadme());
      
      // Add tsconfig.json
      projectFolder.file('tsconfig.json', JSON.stringify({
        compilerOptions: {
          target: "ES2020",
          useDefineForClassFields: true,
          lib: ["ES2020", "DOM", "DOM.Iterable"],
          module: "ESNext",
          skipLibCheck: true,
          moduleResolution: "bundler",
          allowImportingTsExtensions: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: "react-jsx",
          strict: true,
          noUnusedLocals: true,
          noUnusedParameters: true,
          noFallthroughCasesInSwitch: true,
          baseUrl: ".",
          paths: { "@/*": ["./src/*"] }
        },
        include: ["src"],
        references: [{ path: "./tsconfig.node.json" }]
      }, null, 2));

      // Add tailwind.config.js
      projectFolder.file('tailwind.config.js', `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: { extend: {} },
  plugins: [],
};`);

      // Add postcss.config.js
      projectFolder.file('postcss.config.js', `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};`);

      // Create src folder and add project files
      const srcFolder = projectFolder.folder('src');
      if (srcFolder) {
        // Add all project file contents
        Object.entries(fileContents).forEach(([path, content]) => {
          // Remove leading src/ if present
          const cleanPath = path.replace(/^src\//, '');
          srcFolder.file(cleanPath, content);
        });

        // Add main.tsx if not in fileContents
        if (!fileContents['main.tsx'] && !fileContents['src/main.tsx']) {
          srcFolder.file('main.tsx', `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`);
        }

        // Add App.tsx if not present
        if (!fileContents['App.tsx'] && !fileContents['src/App.tsx']) {
          srcFolder.file('App.tsx', `import React from 'react';

function App() {
  return (
    <div className="min-h-screen bg-gray-900 text-green-400 flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold mb-4">${projectName}</h1>
        <p className="text-lg">Built with Matrix DevStudio</p>
      </div>
    </div>
  );
}

export default App;`);
        }

        // Add index.css
        srcFolder.file('index.css', `@tailwind base;
@tailwind components;
@tailwind utilities;

body {
  margin: 0;
  font-family: system-ui, -apple-system, sans-serif;
}`);
      }

      // Add public folder
      const publicFolder = projectFolder.folder('public');
      if (publicFolder) {
        publicFolder.file('favicon.svg', `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <rect width="100" height="100" fill="#111"/>
  <text x="50" y="70" font-size="60" text-anchor="middle" fill="#00ff41">M</text>
</svg>`);

        // Add service worker for PWA
        const sw = generateServiceWorker();
        if (sw) {
          publicFolder.file('sw.js', sw);
        }
      }

      // Add .gitignore
      projectFolder.file('.gitignore', `node_modules
dist
.env
.env.local
*.log`);

      // Generate the ZIP file
      const blob = await zip.generateAsync({ 
        type: 'blob',
        compression: 'DEFLATE',
        compressionOptions: { level: 9 }
      });

      // Create download link
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${projectName}-${projectType}-v${version}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      toast({
        title: "Download Ready!",
        description: `${projectName} package (${Object.keys(fileContents).length} files) exported successfully!`,
      });

      onClose();
    } catch (error) {
      console.error('ZIP generation error:', error);
      toast({
        title: "Generation Failed",
        description: error instanceof Error ? error.message : "Failed to generate project package",
        variant: "destructive",
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const fileCount = Object.keys(fileContents).length;

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-sm flex items-center justify-center z-50">
      <Card className="w-full max-w-2xl mx-4 bg-studio-sidebar border-2 cyber-border neon-glow">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 font-cyber neon-green">
            <FileArchive className="h-5 w-5" />
            PROJECT_EXPORT.SYS
          </CardTitle>
          <CardDescription className="font-terminal matrix-text">
            Export your project as a complete, ready-to-run package ({fileCount} files)
          </CardDescription>
        </CardHeader>
        
        <CardContent className="space-y-6">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="project-type" className="font-terminal neon-purple">Project Type</Label>
              <Select value={projectType} onValueChange={(value: 'react' | 'pc' | 'mobile') => setProjectType(value)}>
                <SelectTrigger className="cyber-border bg-studio-terminal">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent className="cyber-border bg-studio-sidebar">
                  <SelectItem value="react">
                    <div className="flex items-center gap-2">
                      <Globe className="h-4 w-4 neon-green" />
                      React Web App
                    </div>
                  </SelectItem>
                  <SelectItem value="mobile">
                    <div className="flex items-center gap-2">
                      <Smartphone className="h-4 w-4 neon-purple" />
                      Mobile App (WAP/Native)
                    </div>
                  </SelectItem>
                  <SelectItem value="pc">
                    <div className="flex items-center gap-2">
                      <Monitor className="h-4 w-4 neon-cyan" />
                      PC Desktop App
                    </div>
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="project-name" className="font-terminal neon-purple">Project Name</Label>
              <Input
                id="project-name"
                value={projectName}
                onChange={(e) => setProjectName(e.target.value)}
                placeholder="Enter project name"
                className="cyber-border bg-studio-terminal font-terminal"
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="version" className="font-terminal neon-purple">Version</Label>
              <Input
                id="version"
                value={version}
                onChange={(e) => setVersion(e.target.value)}
                placeholder="1.0.0"
                className="cyber-border bg-studio-terminal font-terminal"
              />
            </div>

            {projectType === 'pc' && (
              <div className="space-y-2">
                <Label htmlFor="installer-type" className="font-terminal neon-purple">Installer Type</Label>
                <Select value={installerType} onValueChange={(value: any) => setInstallerType(value)}>
                  <SelectTrigger className="cyber-border bg-studio-terminal">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="cyber-border bg-studio-sidebar">
                    <SelectItem value="exe">Windows (.exe)</SelectItem>
                    <SelectItem value="msi">Windows Installer (.msi)</SelectItem>
                    <SelectItem value="dmg">macOS (.dmg)</SelectItem>
                    <SelectItem value="deb">Linux (.deb)</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}

            {projectType === 'mobile' && (
              <div className="space-y-2">
                <Label htmlFor="mobile-type" className="font-terminal neon-purple">Mobile Platform</Label>
                <Select value={mobileType} onValueChange={(value: any) => setMobileType(value)}>
                  <SelectTrigger className="cyber-border bg-studio-terminal">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent className="cyber-border bg-studio-sidebar">
                    <SelectItem value="wap">WAP (Web App Package)</SelectItem>
                    <SelectItem value="android">Android (.apk)</SelectItem>
                    <SelectItem value="ios">iOS (.ipa)</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            )}
          </div>

          <div className="space-y-4 p-4 rounded-lg bg-studio-terminal cyber-border">
            <div className="flex items-center space-x-2">
              <Checkbox
                id="offline"
                checked={offlineCapable}
                onCheckedChange={(checked) => setOfflineCapable(!!checked)}
              />
              <Label htmlFor="offline" className="flex items-center gap-2 font-terminal matrix-text">
                <Download className="h-4 w-4 neon-green" />
                Enable Offline Capabilities (PWA)
              </Label>
            </div>

            <div className="flex items-center space-x-2">
              <Checkbox
                id="tests"
                checked={includeTests}
                onCheckedChange={(checked) => setIncludeTests(!!checked)}
              />
              <Label htmlFor="tests" className="flex items-center gap-2 font-terminal matrix-text">
                <TestTube className="h-4 w-4 neon-purple" />
                Include Testing Suite (Vitest)
              </Label>
            </div>
          </div>

          <div className="flex justify-between pt-4 border-t cyber-border">
            <Button variant="outline" onClick={onClose} className="cyber-border">
              Cancel
            </Button>
            <Button 
              onClick={handleDownload} 
              disabled={isGenerating}
              className="bg-neon-green text-studio-bg hover:bg-neon-green/90 font-terminal"
            >
              {isGenerating ? (
                <>
                  <div className="animate-spin h-4 w-4 border-2 border-current border-t-transparent rounded-full mr-2" />
                  Generating ZIP...
                </>
              ) : (
                <>
                  <Package className="h-4 w-4 mr-2" />
                  Export Project ({fileCount} files)
                </>
              )}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
};
